[package]
name = "aria"
version = "0.1.0"
edition = "2021"
authors = ["Hiten Patel"]
description = "Sample Rust Application"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
config = "0.14.0"
once_cell = "1.19.0"
rand = "0.8.5"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
